### PR TITLE
Update constraints (for smaller devices)

### PR DESCRIPTION
**Pull request by jontelang**
I use a 5s and the example app was not exactly a beauty to look at, and some constraints were not there.

Screenshot

x

### CODE REVIEW

**Comment by Juanpe** [comment]
Hi @jontelang, thanks for you PR. 🙌🏻
Now, I'm not accepting PR to improve the example project.
I'm going to leave this PR active until then.

**Comment by jontelang** [comment]
I saw this comment on another PR after I had already made it. May I ask why?

**Comment by Juanpe** [comment]
Yeah, sure. Actually I'm working in new features to release them in few weeks. 
Then, I'm modifying the example project to include all new features, so I prefer to leave the PRs related with the example project in stand by until that I create the new structure of the example project. 
I hope you understand it. 🙂

**Comment by jontelang** [comment]
Sure, that kind of makes sense in a way.

**Pull request closed without merging**
