### PR TITLE
Support for using SkeletonView with RxDataSources.

### PR DESCRIPTION
**Pull request by AnyOptional**
As we can see, when using RxDataSources, we can not just use SkeletonView together, so I wrote this code to support for using SkeletonView with RxDataSources.

### CODE REVIEW

**Comment by AnyOptional** [comment]
@Juanpe  Firstly I want to say thank you, thank you for guiding me, I've learned a lot through this work. I didn't think that some of the work I did for myself could help others, thanks for this awesome lib.

**Comment by AnyOptional** [comment]
@Juanpe My English isn't good, I can read and have some simple conversations, but not enough to write a readme file  😂😂😂. l hope that you can understand， if you needs a Chinese version, I might be able to help.

**Comment by Juanpe** [comment]
Yep, no problem. Could you make an easy guide about how to use it? if you feel more comfortable, do it in Chinese, I will try to translate it :)

**Comment by AnyOptional** [comment]
OK, l'll try my best.

**Comment by Juanpe** [comment]
Hey @AnyOptional, how are you going?  need some help? :)

**Comment by AnyOptional** [comment]
@Juanpe I've already made a readme file, isn't good, you may need to make some adjustments to use it 😂.

**Comment by Juanpe** [comment]
no problem, I will do! thank you so much for the effort 👏

**Pull request merged**
