### PR TITLE
Fixes removing skeleton layers from table header footer sections

### PR DESCRIPTION
**Pull request by darkside999**
Fixes Juanpe/SkeletonView#260

### CODE REVIEW

**Comment by Juanpe** [comment]
Hi @darkside999, thanks for the contribution. I've checked the code, and it looks good :)

Just one thing to merge this PR, could you update the CHANGELOG file, please?

You only need to add this PR to the "Next version" section. You can use this template:
* [**{{Pull request Id}}**]({{Pull request URL}}): {{Pull request title}} - [@{{username of PR author}}](link of the profile of PR author)

**Comment by darkside999** [comment]
@Juanpe done :)

**Comment by Juanpe** [comment]
Thanks! it will be available in the next version 🎉

**Comment by kidS2ran** [comment]
@Juanpe  hi, i want to hide Header, footer view, how can i do it

**Comment by mieng18** [comment]
@Juanpe  I have the same problem with @kidS2ran  when tried to do skeletonView with custom Header and custom collectionView . How can we hide it when we do SkeletonView

**Pull request merged**
