### PR TITLE
Add ExampleViewController for programatically creating ViewController

### PR DESCRIPTION
**Pull request by JacksonJang**
### Summary

Describe the goal of this PR. Mention any related Issue numbers.
issue link : https://github.com/Juanpe/SkeletonView/issues/474

I love "SkeletonView" Library. so I've seen this library issue since a year.
I would like to contribute.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/main/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/main/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by Juanpe** [comment]
Hi @JacksonJang 👋🏼 

Thanks for contributing. I like the example but I think the name should be more descriptive, something like: `UITextViewByCodeViewController` or something like that. WDYT?

**Comment by JacksonJang** [comment]
Hello~ Junape^^

Thanks for your answer!
I'm glad every time when I receive your mail regarding git.
"UITextViewByCodeViewController" is a good name, I think so!

Would I have to PR again to change the name?

**Comment by Juanpe** [comment]
Great!

No, you only need to modify the name and commit the changes 👍🏼

**Comment by JacksonJang** [comment]
I changed the name thanks to you!!

**Review by Juanpe — APPROVED** [review]
Thanks 👍🏼 🚢

**Pull request merged**
