### PR TITLE
Implemented state recovering

### PR DESCRIPTION
**Pull request by vskintiyan**
Implemented state recovering for UILabel, UIImage, UITextView and UITextField
Updated example storyboard

### CODE REVIEW

**Comment by Juanpe** [comment]
Hi @vskintiyan, thanks for your pull request. I would want to implement this idea 👍🏼
I would like propose you something: Would be better create an UIView property with a struct called, ViewState or RecoveryViewState?. This property would contains all data needed for recovery the view state. What do you think?

**Comment by Juanpe** [comment]
Hi @vskintiyan, what do you think about my comment?

**Comment by vskintiyan** [comment]
Hi @Juanpe, I think it would be better to save specific properties for concrete classes. Having one general struct for UIView in my opinion is overkill. What do you think?

**Comment by Juanpe** [comment]
Mm..saving specific properties we are duplicating the code.
For example, the UILabels, UITextViews, UIImageViews... have ```recoverBackgroundColor```, so we would need to define the recoverBackgroundColor in the all classes. However, these elements are UIViews, so we would reduce the code and we would work less if we create the property in the UIView extension, right?
Another problem, if we create multiples "recover" properties, when we want to modify some one, we should update all properties

**Comment by vskintiyan** [comment]
Yeah, that make sense. I'm considering using some `var storage: Dictionary<String, AnyObject>` for UIView extension instead of "god" struct. So we could backup and recover values for keys specified localy and privatly.

**Comment by Juanpe** [comment]
Maybe, we could create a ```var backupViewState: ViewState``` where ```ViewState``` is a struct with the view properties, like ```backgroundColor``` or ```text```. 
Do you know what I mean?

**Comment by vskintiyan** [comment]
Sure. But having one common 'ViewState' is a bit heavy, don't you think?  On the other hand we could have a dictionary. And UIView subclasses should only update it with its own keys. I think it is more clean solution.

**Comment by Juanpe** [comment]
Mm...ok. In this case, if we use Dictionary, I would create, for sure, an enum with DictionaryKeys, to only allow our keys. 
```Dictionary<UIViewRecoveryKey, AnyObject>```
Something like this:
```swift
enum UIViewRecoveryKey: String {
  case BackgroundColor
  case Text
  ....
}
```
or
```swift
enum UIViewRecoveryKey {
  static let backgroundColor = "BackgroundColorKey"
  static let text = "Text"
  ....
}
```

What do you think?

**Comment by vskintiyan** [comment]
To allow only our keys we implement the internal extension for 'UIView'. But if you want more restrict recover dictionary we could use `protocol UIViewRecoveryKey {}` to conform our 'enum's. So having 'Dictionary<UIViewRecoveryKey, AnyObject>' in UIView extension and 
```
enum UILabelRecoveryKey: String {...}
extension UILabelRecoveryKey: UIViewRecoveryKey {}
```
in UILabel extension would separate the concrete recover implementation for specific 'UIView' subclasses.
Sorry for the late response.

**Pull request closed without merging**
