### PR TITLE
Fix: Skeleton loading for UICollectionView

### PR DESCRIPTION
**Pull request by kjoneandrei**
fixed Skeleton loading for UICollectionView by adding a prepareSkeleton function for UICollectionView
(Fixes Issue: https://github.com/Juanpe/SkeletonView/issues/41)

This will prepare the UICollectionView by laying out the cells so we can apply skeleton to them
Before the cells used to be layed out after the animation stated causing the cells not to animate

Also I have created an Example Project for the UICollectionView

This will not break any of the existing functionality

### CODE REVIEW

**Comment by i3yamazaki** [comment]
Hope to merge this  one !!

**Comment by orlandoamorim** [comment]
Applying the same logic used here in UITableView solves the problem with NIBs files as well. I did it and it worked here.

**Comment by ed-mejia** [comment]
@orlandoamorim  how did you get it working with TableViews? I did the same and I can get the skeleton to work properly on the cells loading via xib :(

**Comment by yanaoto** [comment]
As shown in the following code, I confirmed that it works in the collection view when executed on the main thread.
```
DispatchQueue.main.async {[weak self] in
             self? .view.showAnimatedGradientSkeleton()
         }
```

**Comment by ivangodfather** [comment]
when this will be merged? its so annoying that you cant register cells from xib

**Comment by luangs7** [comment]
is there a similar component to use with UICollectionView where I can register a cell from xib?

**Comment by luangs7** [comment]
@kjoneandrei do you have some example? What I know so far is: set startSkeletonAnimation inside xib`s controller

**Comment by luangs7** [comment]
@kjoneandrei I'm glad for your time to help me! I tried a similar way like you did, but the skeleton is animate the hole `UICollectionView`, not the xib (I dont know if I'm expressing myself right in this part).

I don't get if I'm doing something wrong or missin something

**Comment by kjoneandrei** [comment]
@luangs7 indeed, sadly until this gets merged that will happen, but if you would use this path for your carthage, pods file, it will work, since the fixes are contained to this branch only 

Taken from my `Cartfile`
`github "kjoneandrei/SkeletonView" "feature/fix_skeleton_collectionView"`

**Comment by Juanpe** [comment]
Hi @kjoneandrei, I’m going to merge this PR, but first you need to solve the conflicts. 
Could you solve them, please?
Thanks

**Comment by luangs7** [comment]
@kjoneandrei thanks for your help mate.

**Comment by kjoneandrei** [comment]
@Juanpe will try to fix them maybe today or tomorrow, seems like there were quite a bit of files changed since february so will have to take a careful look

will keep you posted once it is done

**Comment by Juanpe** [comment]
Ok @kjoneandrei, let me know if you need help 😉

**Comment by Juanpe** [comment]
Hi @kjoneandrei, how was the review? could you check the conflicts? Thanks :)

**Comment by kjoneandrei** [comment]
@Juanpe fixed now, let me know if something occurs or you want some changes

**Comment by qclmnt** [comment]
@kjoneandrei can you explain me why we need to prepareSkeleton before showSkeleton for collection view ?
Because it does almost the same that `addDummyDataSource` that is called during presentation of the skeleton 🤔  ? 
And moreover, sometimes I need it to makes my code working, and sometime I need to avoid it to make it work ? I can't understand exactly why it is so useful ?

**Comment by kjoneandrei** [comment]
Hey @qclmnt, as the needs changed, I haven't been using the framework for more than a year, so I can't tell you to be honest, since things seem to have changed across time, but at the time of the PR (~2 years ago) the `UICollectionView` layout was being reset on creation of the skeleton view and `prepareSkeleton` was the way to solve the issue. 

Probably showcasing some code examples as well, of your cases would help in identifying the issues you have, as they might be specific to your use case only?

**Pull request merged**
