### PR TITLE
Add ability to customize line spacing per label

### PR DESCRIPTION
**Pull request by gshahbazian**
Also customizability of edge insets for skeleton rows

### CODE REVIEW

**Comment by Juanpe** [comment]
Hi @gshahbazian, I think it would be better if we can define an UIEdgeInsets instead of set the top padding. What do you think?

**Comment by gshahbazian** [comment]
@Juanpe sounds good, will make that change

**Comment by gshahbazian** [comment]
@Juanpe hows that look?

**Comment by gshahbazian** [comment]
@Juanpe done

**Pull request merged**
