### PR TITLE
Add support skeletonable headers and footers of UITableView and UICollectionView

### PR DESCRIPTION
**Pull request by nikitskynikita**
The solution to the problem described in #207.

### CODE REVIEW

**Comment by lowki93** [comment]
Nice

**Comment by lowki93** [comment]
@DSchechter do you know when i can be merge ?

**Comment by DSchechter** [comment]
Someone with write access to the repo needs the approve (which I don't have). Until then, it can't be merged

**Comment by KrishnaKaira** [comment]
@nikitskynikita 
Well done.
Are those changes merged ?

**Comment by CapeFurSeal** [comment]
Was this tested? I cannot seem to animate my header view in my tableview. identifierForHeaderInSection in SkeletonTableViewDataSource never gets called?

**Comment by nikitskynikita** [comment]
Hello, I have added a header and footer for the UITableView example. Sorry for the long pause.

**Comment by CapeFurSeal** [comment]
This does not animate the label inside the header view. It only makes the whole header cell the default color. When you change the gradient color in the example, the header colors stay the same and do not change accordingly.

**Comment by KrishnaKaira** [comment]
@Juanpe could you please check and merge the changes with next release?

**Comment by MamtaKukreja** [comment]
@Juanpe I am somehow unable to use this through pod. I tried to update the pod too. Can you check if it is available in pod 1.8.2?

**Comment by adika-juniarsa** [comment]
yes please release this in v1.8.3

**Comment by MamtaKukreja** [comment]
@adika-juniarsa I see the pod updated 3 days ago, and I do not face this issue anymore. Just informing incase you didn't get a change to come back to this.

**Comment by MamtaKukreja** [comment]
@Juanpe I am still unable to make the header and footer skeletonable by providing header and footer identifiers. Both these methods are not called at all.

**Comment by Juanpe** [comment]
Hi @MamtaKukreja, please, could you create an issue? In order to share with other developers the status

**Comment by guramijobava** [comment]
@Juanpe 
I have currently updated from 1.8.2 to 1.8.7.  After some investigation, these changes seems to be merged in 1.8.3, which actually broke my custom tableView (different heights for each row and content) with lots of additional warnings in the debug console.

I'll make the merge request in few minutes already found which line of code helps to resolve it. Please test it first, before releasing it or making a pull request, so the community that is using it doesn't face broken table views without any explanation (by the way, thanks @Juanpe for maintaining it really).

**Pull request merged**
