### PR TITLE
Fixed: UITextField placeholder text is visible while skeleton is showing

### PR DESCRIPTION
**Pull request by keshavamurthy1**
…ing #345

Setting placeholder to nil on prepareViewForSkeleton() method
Created RecoverableTextFieldState, which has textColor and placeholder properties, 
Added UITextField extension in Recoverable.swift
Setting the values back to UITextField properties on recoverViewStage method with 'forced' parameter is true

### Summary

Describe the goal of this PR. Mention any related Issue numbers.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/Juanpe/SkeletonView/blob/develop/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/Juanpe/SkeletonView/blob/develop/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by Juanpe** [comment]
Hi @keshavamurthy1, please, could you update your branch, it seems something is failing. I've updated the CI system, so it's possible that your branch works fine

**Comment by Juanpe** [comment]
Hi @keshavamurthy1, could you update your branch, it seems something is failing. I've updated the CI system, so now your branch would be working fine

**Comment by keshavamurthy1** [comment]
@Juanpe done, all checks are passed now.

**Comment by Juanpe** [comment]
Yeah, now it looks great 🤙 

Thanks again for contributing ;)

**Pull request merged**
