### PR TITLE
Support dark mode

### PR DESCRIPTION
**Pull request by Wilsonator5000**
This pull request adds support for iOS 13 dark mode by using adaptive UIColors and swizzling `traitCollectionDidChange(_:)`, and changes the default color from `.clouds` to the new `.skeletonDefault` (which is the same as `.clouds` but with a dark variant). It should resolve both #192 and #197.

I also updated the example app to support dark mode, and added my changes to the English README — I'll need some help translating my changes to the other languages, though. Let me know what you think!

### CODE REVIEW

**Comment by Juanpe** [comment]
Hi @Wilsonator5000, thanks for contributing!

Please, could you update the [CHANGELOG](https://github.com/Juanpe/SkeletonView/blob/master/CHANGELOG.md) file too?

Thanks!

**Comment by Wilsonator5000** [comment]
@Juanpe OK, I updated the CHANGELOG!

**Comment by Wilsonator5000** [comment]
Hey @Juanpe, what's the status on this PR? Thanks 😄

**Comment by Juanpe** [comment]
Thanks for contributing @Wilsonator5000 :)

**Pull request merged**
