### PR TITLE
Improve ui label behaviour

### PR DESCRIPTION
**Pull request by vcsabi**

### CODE REVIEW

**Comment by Juanpe** [comment]
Hi @vcsabi, thanks for your PRs. I've checked the PR, but I don't know exactly what do you mean with these changes. Could you give more info about?
Thanks

**Comment by strfn** [comment]
I'm having the same issue with labels and agree the height constraints should not be required.

**Comment by Dfmarulanda** [comment]
Why this wasn't approved?

**Comment by vcsabi** [comment]
Now I understand because I wanted to use it differently. Both ways are ok in my opinion. Mine is a lot more "restricted". Maybe we should be able to change if we want to use the same size as the label's text or the default one

**Comment by MortyMerr** [comment]
Should be merged, cause removing placeholder text form label is a very strange solution.

**Comment by Juanpe** [comment]
Hi! this PR will be closed since version 1.8 solves this problem 
Thanks for the contribution :)

**Pull request closed without merging**
